# Generated by Django 3.0.6 on 2020-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('issuetype', models.CharField(default='Blank/Frozen Screen', max_length=40)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Work in Progress', 'Work in Progress'), ('Closed', 'Closed')], default='Open', max_length=40)),
                ('desc', models.TextField()),
            ],
        ),
    ]
